### ISSUE TITLE
update examples with old urls

### ISSUE THREAD

**Issue by emaxerrno** [smfrpc/smf-go#3]
currently the example folder has imports like 

https://github.com/smfrpc/smf-go/blob/master/example/demo_client/main.go

```
	"github.com/crackcomm/go-smf/example/demo"
	"github.com/crackcomm/go-smf/example/demo_gen"
	"github.com/crackcomm/go-smf/smf"
```

We should fix so we get the right imports and ppl can use the code 

/cc @crackcomm

**Comment by emaxerrno** [comment]
@crackcomm  - awesome, thanks for the fix. 

I think to keep everyone in the loop, it would be good to still open a PR instead of committing to master, and waiting for CI to greenlight the build. 

THanks for the speedy commit tho ! :) :1st_place_medal:  :+1:

**Comment by crackcomm** [comment]
@senior7515 ok :)
